name: Build and Test
on:
  push:
    paths:
      - 'DevOps-for-Developers/CI-CD-in-GitHub-Actions-Exercise/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'DevOps-for-Developers/CI-CD-in-GitHub-Actions-Exercise/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DevOps-for-Developers/CI-CD-in-GitHub-Actions-Exercise/01-02-Student-Registry-App
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci   
    - name: Run tests
      run: npm test